# Generated by Django 2.2.2 on 2019-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0002_insureduser_nokactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
