# Generated by Django 2.2.2 on 2019-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0003_submission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureduser',
            name='picurl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
