# Generated by Django 2.2.2 on 2019-07-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0007_auto_20190707_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_logic.CommonUser'),
        ),
    ]
